title: RubyLLM
description: A delightful Ruby way to work with AI
url: https://rubyllm.com
baseurl: /
remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure
nav_external_links:
  - title: RubyLLM on GitHub
    url: https://github.com/crmne/ruby_llm
    hide_icon: false

# Footer content
footer_content: "Copyright &copy; 2025 <a href='https://paolino.me'>Carmine Paolino</a>. Distributed under an <a href=\"https://github.com/crmne/ruby_llm/tree/main/LICENSE\">MIT license.</a>"

# Enable copy button on code blocks
enable_copy_code_button: true

# Make Anchor links show on hover
heading_anchors: true

# Color scheme
color_scheme: light

# Google Analytics
ga_tracking:
ga_tracking_anonymize_ip: true

# Custom plugins (GitHub Pages allows these)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
